---
- name: Install message queue service packages
  yum: state=present name={{ item }}
  with_items:
  - rabbitmq-server

- name: Start message queue service
  service: name=rabbitmq-server state=started enabled=yes

- name: Create rabbitmq user
  rabbitmq_user: user={{ rabbitmq_user }}
                 password={{ rabbitmq_password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  run_once: true
